defaults: &defaults
  foursquare:
    key: "WKBZNVCJI3TYZ5NGG0E1HGTGMKRFEBD00TOTHDDIUKHMDNQS"
    secret: "42M0A4Q5032OHNJKZD0V4LZ1DDSE3MZ4KCYDZMFWRXYCR4OX"
    userpage: "http://foursquare.com/user/:uid"

  facebook:
    key: "532653103430025"
    secret: "8a1bb09b869e4cf37318fa1b29b3652a"
    userpage: "http://facebook.com/:uid"

  twitter:
    key: "4xM22OmDisiVANPbDPyFA"
    secret: "2IV2C5qz6wTlkzKPnue1IrBlfeQuB4vMPiwYSjUTo"
    userpage: "https://twitter.com/account/redirect_by_id?id=:uid"
    token: "197304568-EQH0OJnEe0AfPsxt4laDN8319kNXBGSRHcItBsxI"
    token_secret: "2dJKZmDA3ffZdX33DOAx2Ww356OXbbBR99kTGTEtM"

  host: "wheremymates.dev"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  foursquare:
    key: "IKQQ0UN1VV2BMNZ2M2R1R1M5X1JFGBTJGOS4EJL22QOFYVGG"
    secret: "KF5XH4LZIU05IUALNKO1MPOHJUFHZEICKK5CYZHOHCTOIURP"
    userpage: "http://foursquare.com/user/:uid"

  facebook:
    key: "187683721368319"
    secret: "86ff11f9d5eea3cf1dd2992736581668"
    userpage: "http://facebook.com/:uid"

  twitter:
    key: "GmAbR0ADOFB6upYe1Ui3ZQ"
    secret: "6ZWUfH55sqG3trBNADQIeo6VW6B5c28m3bjPBmvGYg"
    userpage: "https://twitter.com/account/redirect_by_id?id=:uid"
    token: "197304568-GSun6ZLHmTZDtCE8frLMih7WWf1gVjo7FalJRjm5"
    token_secret: "3498V4AT0FAS8nLxT0pdGy1tAYH4pkShfFgU40ALJc"

  host: "wheremymates.com"
