defaults: &defaults
  foursquare_key: "QOUC2ILLMDQ2UQMFOPLQJ4OTGBDG2R1UKBSMH5M5G15BOZTF"
  foursquare_secret: "ZXYLOXLP33Q2EAYJVJJLQFGFSW0VNB14NRH2FE4CKHOHVDEW"

  facebook_key: "376432435769798"
  facebook_secret: "c39c4bf6abfa459abd55435a602ca736"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  foursquare_key: "IKQQ0UN1VV2BMNZ2M2R1R1M5X1JFGBTJGOS4EJL22QOFYVGG"
  foursquare_secret: "KF5XH4LZIU05IUALNKO1MPOHJUFHZEICKK5CYZHOHCTOIURP"

  facebook_key: "187683721368319"
  facebook_secret: "86ff11f9d5eea3cf1dd2992736581668"
