defaults: &defaults
  foursquare:
    key: "WKBZNVCJI3TYZ5NGG0E1HGTGMKRFEBD00TOTHDDIUKHMDNQS"
    secret: "42M0A4Q5032OHNJKZD0V4LZ1DDSE3MZ4KCYDZMFWRXYCR4OX"
    userpage: "http://foursquare.com/user/:uid"

  facebook:
    key: "532653103430025"
    secret: "8a1bb09b869e4cf37318fa1b29b3652a"
    userpage: "http://facebook.com/:uid"

  host: "wheremymates.dev"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  foursquare:
    key: "IKQQ0UN1VV2BMNZ2M2R1R1M5X1JFGBTJGOS4EJL22QOFYVGG"
    secret: "KF5XH4LZIU05IUALNKO1MPOHJUFHZEICKK5CYZHOHCTOIURP"

  facebook:
    key: "187683721368319"
    secret: "86ff11f9d5eea3cf1dd2992736581668"

  host: "wheremymates.com"
